POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0M2I3MzJkNWZiODJkYTIzZmY2YjdjYiIsImlhdCI6MTY4MTY2Mzk3N30.0CxDgQ2UO1JrmMNOCJ9nT7Fe7i_pyn-SLhjpnJotyPg

{
  "title": "My Toes4",
  "author": "My Knees5",
  "url": "My Shoulders6",
  "likes": 101
  }

